{
 "title": "Weather",
 "description": "RTL_SDR Based Weather Data Collection",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Combined Temperature Display",
   "type": "graph",
   "description": "- Yard Sensor: Acurite 3-in-1 Weather Sensor\n- Garage Sensor: Acurite Tower Sensor in Garage\n- Data Closet Sensor: Accurite Temp/Humidity Sensor in Data Closet\n- Tower Sensor: Neighbor device, unknown location",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal AS \"Yard Sensor\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal AS \"Garage Sensor\"\nFROM weather\nwhere \n(data -> 'tags' ->> 'id') like '9359'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal AS \"Data Closet Sensor\"\nFROM weather\nwhere \n(data -> 'tags' ->> 'id') like '13064'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY 1;\n"
    },
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal AS \"Tower Sensor\"\nFROM weather\nwhere \n(data -> 'tags' ->> 'id') like '6104'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(35.74 \n+ (0.6215 * ((data -> 'fields' ->> 'temperature_F')::decimal)) \n- (35.75 * ((data -> 'fields' ->> 'wind_speed_mph')::decimal)^0.16)\n+(0.4275 * ((data -> 'fields' ->> 'temperature_F')::decimal) * ((data -> 'fields' ->> 'wind_speed_mph')::decimal)^0.16)) \nAS \"Wind Chill\"\nFROM weather\nWHERE\n(data -> 'fields' ->> 'wind_speed_mph')::decimal >= 4\nAND\n(data -> 'fields' ->> 'temperature_F')::decimal <= 40\nAND\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(-42.379\n+ (2.04901523 * ((data -> 'fields' ->> 'temperature_F')::decimal)) \n+ (10.1433313 * ((data -> 'fields' ->> 'humidity')::decimal)) \n- (0.22475541 * ((data -> 'fields' ->> 'temperature_F')::decimal) * ((data -> 'fields' ->> 'humidity')::decimal)) \n- (0.00683783 * ((data -> 'fields' ->> 'temperature_F')::decimal)^2) \n- (0.05481717 * ((data -> 'fields' ->> 'humidity')::decimal)^2) \n+ (0.00122874 * ((data -> 'fields' ->> 'temperature_F')::decimal)^2 * (data -> 'fields' ->> 'humidity')::decimal)\n+ (0.00085282 * ((data -> 'fields' ->> 'temperature_F')::decimal) * ((data -> 'fields' ->> 'humidity')::decimal)^2) \n- (0.00000199 * ((data -> 'fields' ->> 'temperature_F')::decimal)^2 * ((data -> 'fields' ->> 'humidity')::decimal)^2))\nAS \"Heat Index\"\nFROM weather\nWHERE\n(data -> 'fields' ->> 'temperature_F')::decimal >= 80\nAND\n(data -> 'fields' ->> 'humidity')::decimal >= 40\nAND\n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nAND\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Yard Sensor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal as \"Temp\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Tower Sensor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal as \"Temp\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite tower sensor'\nand\n(data -> 'tags' ->> 'channel') like 'A'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Garage Sensor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal as \"Temp\"\nFROM weather\nwhere \n(data -> 'tags' ->> 'id') like '9359'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Data Closet Sensor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal as \"Temp\"\nFROM weather\nwhere \n(data -> 'tags' ->> 'id') like '13064'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Outdoor Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'humidity')::decimal as \"Humidity\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "velocitymph", "label": "Wind Speed" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'wind_speed_mph')::decimal AS \"Wind Speed\"\nFROM weather\nwhere \n--(data -> 'fields' ->> 'wind_speed_mph') is not null\n--and\n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    {
     "format": "dB",
     "label": "Received Signal Strength Indicator"
    }
   ],
   "targets": [
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"LaCrosse\"\nfrom weather\nwhere (data ->> 'measurement') like 'LaCrosse TX141-Bv2 sensor'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\norder by 1,2;\n"
    },
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"Yard Sensor\"\nfrom weather\nwhere (data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\norder by 1,2;\n"
    },
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"Tower Sensor\"\nfrom weather\nwhere\n(data -> 'tags' ->> 'id') like '6104'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\norder by 1,2;\n"
    },
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"Garage Sensor\"\nfrom weather\nwhere \n(data -> 'tags' ->> 'id') like '9359'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\norder by 1,2;\n"
    },
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"Data Closet Sensor\"\nfrom weather\nwhere \n(data -> 'tags' ->> 'id') like '13064'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\norder by 1,2;\n"
    }
   ]
  },
  {
   "title": "All Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM weather ORDER BY id DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Indoor Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'humidity')::decimal as \"Humidity\"\nFROM weather\nwhere \n(data -> 'tags' ->> 'id') like '13064'\nand\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo()\nORDER BY time desc\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Current Time Window",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(*)\nfrom weather\nwhere\n(data ->> 'time')::timestamp with time zone between $__timeFrom() and $__timeTo();"
    }
   ]
  }
 ]
}