{
 "title": "Weather",
 "description": "RTL_SDR Based Weather Data Collection",
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Combined Temperature Display",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal AS \"Yard Sensor\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;\n"
    },
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal AS \"Garage Sensor\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite tower sensor'\nand\n(data -> 'tags' ->> 'channel') like 'C'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;\n"
    },
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal AS \"Tower Sensor\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite tower sensor'\nand\n(data -> 'tags' ->> 'channel') like 'A'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Yard Sensor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal as \"Temp\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Tower Sensor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal as \"Temp\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite tower sensor'\nand\n(data -> 'tags' ->> 'channel') like 'A'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Garage Sensor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'temperature_F')::decimal as \"Temp\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite tower sensor'\nand\n(data -> 'tags' ->> 'channel') like 'C'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "All Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\ncount(*)\nfrom weather;"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'humidity')::decimal as \"Humidity\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "velocitymph", "label": "Wind Speed" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'wind_speed_mph')::decimal AS \"Wind Speed\"\nFROM weather\nwhere \n(data -> 'fields' ->> 'wind_speed_mph') is not null\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 12 },
   "yaxes": [
    {
     "format": "dB",
     "label": "Received Signal Strength Indicator"
    }
   ],
   "targets": [
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"LaCrosse\"\nfrom weather\nwhere (data ->> 'measurement') like 'LaCrosse TX141-Bv2 sensor'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\norder by 1,2;\n"
    },
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"Wind Sensor\"\nfrom weather\nwhere (data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\norder by 1,2;\n"
    },
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"Tower Sensor\"\nfrom weather\nwhere (data ->> 'measurement') like 'Acurite tower sensor'\nand\n(data -> 'tags' ->> 'channel') like 'A'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\norder by 1,2;\n"
    },
    {
     "rawSql": "select\n(data ->> 'time')::timestamp with time zone AS \"time\",\n(data -> 'fields' ->> 'rssi')::real as \"Garage Sensor\"\nfrom weather\nwhere (data ->> 'measurement') like 'Acurite tower sensor'\nand\n(data -> 'tags' ->> 'channel') like 'C'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\norder by 1,2;\n"
    }
   ]
  },
  {
   "title": "Current Time Window",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\ncount(*)\nfrom weather\nwhere\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo();"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 18 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'time')::timestamp with time zone AS \"time\",\n  (data -> 'fields' ->> 'humidity')::decimal as \"Humidity\"\nFROM weather\nwhere \n(data ->> 'measurement') like 'Acurite 3n1 sensor'\nand\n(data ->> 'time')::timestamp with time zone >= $__timeFrom()\nand \n(data ->> 'time')::timestamp with time zone <= $__timeTo()\nORDER BY time;\n"
    }
   ]
  }
 ]
}